Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$ScriptName = 'rijan_wa-windows-installer'

function Info([string]$Message) { Write-Host "[$ScriptName] $Message" }
function Warn([string]$Message) { Write-Warning "[$ScriptName] $Message" }
function Fail([string]$Message) {
  Write-Host "[$ScriptName] ERROR: $Message" -ForegroundColor Red
  exit 1
}

function Test-Command([string]$Name) {
  return $null -ne (Get-Command $Name -ErrorAction SilentlyContinue)
}

function Get-RepoRoot {
  # scripts/installation/windows.ps1 -> repo root
  return (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
}

function New-RandomAlphaNumeric([int]$Length) {
  if ($Length -lt 1) { throw 'Length must be >= 1' }

  $chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
  $bytes = New-Object byte[] $Length
  [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)

  $sb = New-Object System.Text.StringBuilder
  foreach ($b in $bytes) {
    [void]$sb.Append($chars[$b % $chars.Length])
  }
  return $sb.ToString()
}

function Get-Sha256HexLower([string]$InputText) {
  $sha = [System.Security.Cryptography.SHA256]::Create()
  try {
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($InputText)
    $hash = $sha.ComputeHash($bytes)
    return ([System.BitConverter]::ToString($hash) -replace '-', '').ToLowerInvariant()
  } finally {
    $sha.Dispose()
  }
}

function Ensure-DockerPresent {
  if (-not (Test-Command 'docker')) {
    $url = 'https://docs.docker.com/desktop/setup/install/windows-install/'
    Fail "Docker is not installed. Please install Docker Desktop first: $url"
  }

  try {
    docker version | Out-Null
  } catch {
    $url = 'https://docs.docker.com/desktop/'
    Fail "Docker is installed but not working. Please start Docker Desktop and try again. Docs: $url"
  }

  try {
    docker compose version | Out-Null
  } catch {
    $url = 'https://docs.docker.com/compose/install/'
    Fail "Docker Compose v2 is not available (docker compose). Please update Docker Desktop: $url"
  }
}

function Write-EnvFile([string]$InstallDir, [int]$MasterPasswordLen) {
  $envPath = Join-Path $InstallDir '.env'

  if (Test-Path $envPath) {
    Warn ".env already exists at $envPath - backing up to .env.bak"
    Copy-Item -Force $envPath (Join-Path $InstallDir '.env.bak')
  }

  $masterPassword = New-RandomAlphaNumeric -Length $MasterPasswordLen
  $masterKeyHash = Get-Sha256HexLower -InputText $masterPassword

  if ($masterKeyHash.Length -ne 64) {
    throw 'Generated MASTER_KEY hash is invalid (expected 64 hex chars).'
  }

  $content = @(
    "# Generated by $ScriptName at $(Get-Date -Format o)",
    "NODE_ENV=production",
    "PORT=3000",
    "LOG_LEVEL=info",
    "TIMEZONE=Asia/Jakarta",
    "",
    "# IMPORTANT:",
    "# - This value MUST be a SHA256 hex hash (64 chars).",
    "# - Use the *plain* master password (printed below) in request header: X-Master-Key",
    "MASTER_KEY=$masterKeyHash",
    "",
    "# Database inside container (docker-compose.yml uses this path)",
    "DATABASE_PATH=/app/data/rijan_wa.db",
    "",
    "RATE_LIMIT_MAX=100",
    "RATE_LIMIT_WINDOW=60000",
    "ENCRYPTION_ALGORITHM=aes-256-gcm"
  ) -join "`n"

  Set-Content -Path $envPath -Value $content -Encoding UTF8

  return @{
    EnvPath = $envPath
    MasterPassword = $masterPassword
    MasterKeyHash = $masterKeyHash
  }
}

function Write-ComposeFile([string]$InstallDir, [string]$ImageRepo, [string]$ImageTag, [int]$HostPort) {
  $composePath = Join-Path $InstallDir 'docker-compose.yml'

  if (Test-Path $composePath) {
    $backupPath = "$composePath.bak.$(Get-Date -Format 'yyyyMMddHHmmss')"
    Warn "docker-compose.yml already exists; backing up to: $backupPath"
    Copy-Item -Force $composePath $backupPath
  }

  Info 'Writing docker-compose.yml (env_file-driven)...'
  $compose = @(
    'services:',
    '  rijan_wa:',
    "    image: $ImageRepo`:$ImageTag",
    '    container_name: rijan_wa',
    '    restart: unless-stopped',
    '    ports:',
    "      - ""${HostPort}:3000""",
    '    env_file:',
    '      - .env',
    '    volumes:',
    '      - rijan_wa_data:/app/data',
    '      - rijan_wa_sessions:/app/sessions',
    '      - rijan_wa_logs:/app/logs',
    '',
    'volumes:',
    '  rijan_wa_data:',
    '  rijan_wa_sessions:',
    '  rijan_wa_logs:'
  ) -join "`n"

  Set-Content -Path $composePath -Value $compose -Encoding UTF8
  return $composePath
}

function Wait-ForHealthy([string]$ContainerName, [int]$TimeoutSec) {
  $start = Get-Date

  while ($true) {
    $elapsed = (New-TimeSpan -Start $start -End (Get-Date)).TotalSeconds
    if ($elapsed -gt $TimeoutSec) {
      Warn "Timed out waiting for container '$ContainerName' to become healthy."
      Warn "Check logs: docker logs $ContainerName"
      return $false
    }

    $status = ''
    try {
      $status = (docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}no-healthcheck{{end}}' $ContainerName 2>$null).Trim()
    } catch {
      $status = ''
    }

    switch ($status) {
      'healthy' { Info 'Container is healthy.'; return $true }
      'no-healthcheck' { Warn 'No Docker healthcheck detected; assuming container is running.'; return $true }
      default { Start-Sleep -Seconds 2 }
    }
  }
}

function Invoke-Docker([scriptblock]$Block, [string]$ErrorMessage) {
  & $Block
  if ($LASTEXITCODE -ne 0) {
    Fail "$ErrorMessage (exit code: $LASTEXITCODE)"
  }
}

# -------- Main --------

$ImageRepo = if ($env:RIJAN_WA_IMAGE_REPO) { $env:RIJAN_WA_IMAGE_REPO } else { 'teguh02/rijan_wa' }
$ImageTag  = if ($env:RIJAN_WA_IMAGE_TAG)  { $env:RIJAN_WA_IMAGE_TAG }  else { 'latest' }
$InstallDir = if ($env:RIJAN_WA_INSTALL_DIR) { $env:RIJAN_WA_INSTALL_DIR } else { (Get-RepoRoot) }

$HostPort = 3000
if ($env:RIJAN_WA_HOST_PORT) {
  if (-not [int]::TryParse($env:RIJAN_WA_HOST_PORT, [ref]$HostPort)) {
    Fail 'RIJAN_WA_HOST_PORT must be a number.'
  }
}
if ($HostPort -lt 1 -or $HostPort -gt 65535) {
  Fail 'RIJAN_WA_HOST_PORT must be between 1 and 65535.'
}

$MasterLen = 16
if ($env:RIJAN_WA_MASTER_PASSWORD_LEN) {
  if (-not [int]::TryParse($env:RIJAN_WA_MASTER_PASSWORD_LEN, [ref]$MasterLen)) {
    Fail 'RIJAN_WA_MASTER_PASSWORD_LEN must be a number (12-20).'
  }
}
if ($MasterLen -lt 12 -or $MasterLen -gt 20) {
  Fail 'RIJAN_WA_MASTER_PASSWORD_LEN must be between 12 and 20.'
}

Info "Install dir: $InstallDir"
Info "Image: $ImageRepo`:$ImageTag"
Info "Host port: $HostPort -> container 3000"

Ensure-DockerPresent

New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null

# Generate and print credentials FIRST (before any Docker pull/run)
Info 'Generating new .env (MASTER_KEY)...'
$envResult = Write-EnvFile -InstallDir $InstallDir -MasterPasswordLen $MasterLen

Write-Host ''
Write-Host '================= IMPORTANT OUTPUT ================='
Write-Host ("Install dir       : {0}" -f $InstallDir)
Write-Host ("Docker image      : {0}`:{1}" -f $ImageRepo, $ImageTag)
Write-Host ("Env file          : {0}" -f $envResult.EnvPath)
Write-Host ''
Write-Host ("MASTER PASSWORD (PLAIN TEXT)   : {0}" -f $envResult.MasterPassword)
Write-Host ("MASTER_KEY (SHA256 in .env)    : {0}" -f $envResult.MasterKeyHash)
Write-Host ''
Write-Host 'Use this header for admin API:'
Write-Host ("  X-Master-Key: {0}" -f $envResult.MasterPassword)
Write-Host '===================================================='
Write-Host ''

Info 'Pulling image...'
Invoke-Docker { docker pull "$ImageRepo`:$ImageTag" | Out-Null } 'Failed to pull Docker image'

$composePath = Write-ComposeFile -InstallDir $InstallDir -ImageRepo $ImageRepo -ImageTag $ImageTag -HostPort $HostPort

Info 'Starting rijan_wa via docker compose...'
Push-Location $InstallDir
try {
  Invoke-Docker { docker compose up -d | Out-Null } 'Failed to start via docker compose'
} finally {
  Pop-Location
}

[void](Wait-ForHealthy -ContainerName 'rijan_wa' -TimeoutSec 120)

Info 'Manage service:'
Write-Host ("  cd `"{0}`"" -f $InstallDir)
Write-Host '  docker compose ps'
Write-Host '  docker compose logs -f --tail 200 rijan_wa'
Write-Host '  docker compose restart rijan_wa'
Write-Host '  docker compose down'
Write-Host ''

Info 'Health check:'
Write-Host ("  Invoke-WebRequest http://localhost:{0}/health | Select-Object -ExpandProperty Content" -f $HostPort)

exit 0
